// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlExcelBlazor.Server.Data;

#nullable disable

namespace SqlExcelBlazor.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129210443_InitialWorkflowSystem")]
    partial class InitialWorkflowSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.QueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("QueryViewId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QueryViewId");

                    b.ToTable("QueryParameters");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.QueryView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastExecuted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SqlQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("QueryViews");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.StepResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogDetails")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsFailed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowExecutionResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowExecutionResultId");

                    b.ToTable("StepResults");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Schedule")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.WorkflowExecutionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedSteps")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowExecutionResults");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.WorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnError")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OnSuccess")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Order");

                    b.ToTable("WorkflowSteps");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.QueryParameter", b =>
                {
                    b.HasOne("SqlExcelBlazor.Server.Models.QueryView", "QueryView")
                        .WithMany("Parameters")
                        .HasForeignKey("QueryViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueryView");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.StepResult", b =>
                {
                    b.HasOne("SqlExcelBlazor.Server.Models.WorkflowExecutionResult", "WorkflowExecutionResult")
                        .WithMany("StepResults")
                        .HasForeignKey("WorkflowExecutionResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowExecutionResult");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.WorkflowExecutionResult", b =>
                {
                    b.HasOne("SqlExcelBlazor.Server.Models.Workflow", "Workflow")
                        .WithMany("Executions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.WorkflowStep", b =>
                {
                    b.HasOne("SqlExcelBlazor.Server.Models.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.QueryView", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.Workflow", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.WorkflowExecutionResult", b =>
                {
                    b.Navigation("StepResults");
                });
#pragma warning restore 612, 618
        }
    }
}
