// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlExcelBlazor.Server.Data;

#nullable disable

namespace SqlExcelBlazor.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260130203325_InitialConnectionsTable")]
    partial class InitialConnectionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.Connections.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastTested")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Connections");

                    b.HasDiscriminator().HasValue("Connection");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.Connections.CsvConnection", b =>
                {
                    b.HasBaseType("SqlExcelBlazor.Server.Models.Connections.Connection");

                    b.Property<string>("Delimiter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Encoding")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasHeaders")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("CSV");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.Connections.ExcelConnection", b =>
                {
                    b.HasBaseType("SqlExcelBlazor.Server.Models.Connections.Connection");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasHeaders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorksheetName")
                        .HasColumnType("TEXT");

                    b.ToTable("Connections", t =>
                        {
                            t.Property("FilePath")
                                .HasColumnName("ExcelConnection_FilePath");

                            t.Property("HasHeaders")
                                .HasColumnName("ExcelConnection_HasHeaders");
                        });

                    b.HasDiscriminator().HasValue("Excel");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.Connections.MySqlConnection", b =>
                {
                    b.HasBaseType("SqlExcelBlazor.Server.Models.Connections.Connection");

                    b.Property<int>("ConnectionTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("MySQL");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.Connections.PostgreSqlConnection", b =>
                {
                    b.HasBaseType("SqlExcelBlazor.Server.Models.Connections.Connection");

                    b.Property<int>("ConnectionTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Connections", t =>
                        {
                            t.Property("ConnectionTimeout")
                                .HasColumnName("PostgreSqlConnection_ConnectionTimeout");

                            t.Property("Database")
                                .HasColumnName("PostgreSqlConnection_Database");

                            t.Property("Password")
                                .HasColumnName("PostgreSqlConnection_Password");

                            t.Property("Port")
                                .HasColumnName("PostgreSqlConnection_Port");

                            t.Property("Username")
                                .HasColumnName("PostgreSqlConnection_Username");
                        });

                    b.HasDiscriminator().HasValue("PostgreSQL");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.Connections.SqlServerConnection", b =>
                {
                    b.HasBaseType("SqlExcelBlazor.Server.Models.Connections.Connection");

                    b.Property<int>("ConnectionTimeout")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IntegratedSecurity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrustServerCertificate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.ToTable("Connections", t =>
                        {
                            t.Property("ConnectionTimeout")
                                .HasColumnName("SqlServerConnection_ConnectionTimeout");

                            t.Property("Database")
                                .HasColumnName("SqlServerConnection_Database");

                            t.Property("Password")
                                .HasColumnName("SqlServerConnection_Password");

                            t.Property("Port")
                                .HasColumnName("SqlServerConnection_Port");

                            t.Property("Server")
                                .HasColumnName("SqlServerConnection_Server");

                            t.Property("Username")
                                .HasColumnName("SqlServerConnection_Username");
                        });

                    b.HasDiscriminator().HasValue("SqlServer");
                });

            modelBuilder.Entity("SqlExcelBlazor.Server.Models.Connections.WebServiceConnection", b =>
                {
                    b.HasBaseType("SqlExcelBlazor.Server.Models.Connections.Connection");

                    b.Property<string>("AuthConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultHeadersJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("WebService");
                });
#pragma warning restore 612, 618
        }
    }
}
